In [1]:
pip install numpy

You should consider upgrading via the '/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
# import this library in jnotebook
import numpy as np

In [3]:
np.array ([ "Golgappy" , " Pholki" , "Chhat" , "Shoorma"])


array(['Golgappy', ' Pholki', 'Chhat', 'Shoorma'], dtype='<U8')

In [4]:
food= np.array ([ "Golgappy" , " Pholki" , "Chhat" , "Shoorma"])
food

array(['Golgappy', ' Pholki', 'Chhat', 'Shoorma'], dtype='<U8')

In [6]:
price = np.array ([5 , 5 , 5])
price

array([5, 5, 5])

In [7]:
type (food)

numpy.ndarray

In [8]:
type(price)

numpy.ndarray

In [9]:
len(food)

4

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[0]

'Golgappy'

In [12]:
price.mean()

5.0

In [13]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
#empty
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#spicify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#specific intervel
np.arange (2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
#table
np.arange(7,77,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [23]:
#linespace
np.linespace(1, 10, num=5)

AttributeError: module 'numpy' has no attribute 'linespace'